# Generated by Django 4.1.3 on 2022-12-05 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='public_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('uncomplete', 'uncomplete')], default='uncomplete', max_length=255),
        ),
    ]
